### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by thebongy** [csivitu/BroBot#1]
@all-contributors add @alias-rahil for code

**Comment by thebongy** [comment]
@all-contributors add @alias-rahil for code

**Comment by thebongy** [comment]
@alias-rahil Move the repo here too, i'll close this issue after that

**Comment by alias-rahil** [comment]
> @alias-rahil Move the repo here too, i'll close this issue after that
Submitted a [PR](https://github.com/csivitu/BroBot/pull/3) for it.
